from SweetPlots.utilities import PSet

QCD = PSet(
    FileName = "QCD_Pythia_All.root",
    DisplayName = "QCD",
    DrawOption = "HISTE",
    LineColor = 8,
    LineWidth = 2,
    LineStyle = 1,
    FillColor = 8,
    FillStyle = 3003,
    MarkerColor = 8,
    MarkerStyle = 1,
    Weight = 1.,
)
PhotonPlusJet = PSet(
    FileName =  "PhotonJet_Pythia_All.root",
    DisplayName = "#gamma + jet",
    DrawOption = "HISTE",
    LineColor = 5,
    LineWidth = 2,
    LineStyle = 1,
    FillColor = 5,
    FillStyle = 0,
    MarkerColor = 5,
    MarkerStyle = 1,
    Weight = 1.,
)
ttbar = PSet(
    FileName = "TTbarJets.root",
    DisplayName = "ttbar",
    DrawOption = "HISTE",
    LineColor = 4,
    LineWidth = 2,
    LineStyle = 1,
    FillColor = 4,
    FillStyle = 0,
    MarkerColor = 4,
    MarkerStyle = 1,
    Weight = 1.,
)
Wjets = PSet(
    FileName = "WJets.root",
    DisplayName = "W + jets",
    DrawOption = "HISTE",
    LineColor = 4,
    LineWidth = 2,
    LineStyle = 3,
    FillColor = 4,
    FillStyle = 0,
    MarkerColor = 4,
    MarkerStyle = 1,
    Weight = 1.,
)
Zjets = PSet(
    FileName = "ZJets.root",
    DisplayName = "Z + jets",
    DrawOption = "HISTE",
    LineColor = 1,
    LineWidth = 2,
    LineStyle = 3,
    FillColor = 1,
    FillStyle = 0,
    MarkerColor = 1,
    MarkerStyle = 1,
    Weight = 1.,
)
GM1b = PSet(
    FileName = "GM1b.root",
    DisplayName = "GM1b",
    DrawOption = "HISTE",
    LineColor = 2,
    LineWidth = 2,
    LineStyle = 1,
    FillColor = 2,
    FillStyle = 0,
    MarkerColor = 2,
    MarkerStyle = 1,
    Weight = 1.,
)
GM1c = PSet(
    FileName = "GM1c.root",
    DisplayName = "GM1c",
    DrawOption = "HISTE",
    LineColor = 2,
    LineWidth = 2,
    LineStyle = 1,
    FillColor = 2,
    FillStyle = 0,
    MarkerColor = 2,
    MarkerStyle = 1,
    Weight = 1.,
)
GM1d = PSet(
    FileName = "GM1d.root",
    DisplayName = "GM1d",
    DrawOption = "HISTE",
    LineColor = 2,
    LineWidth = 2,
    LineStyle = 1,
    FillColor = 2,
    FillStyle = 0,
    MarkerColor = 2,
    MarkerStyle = 1,
    Weight = 1.,
)
GM1e = PSet(
    FileName = "GM1e.root",
    DisplayName = "GM1e",
    DrawOption = "HISTE",
    LineColor = 2,
    LineWidth = 2,
    LineStyle = 1,
    FillColor = 2,
    FillStyle = 0,
    MarkerColor = 2,
    MarkerStyle = 1,
    Weight = 1.,
)
GM1f = PSet(
    FileName = "GM1f.root",
    DisplayName = "GM1f",
    DrawOption = "HISTE",
    LineColor = 2,
    LineWidth = 2,
    LineStyle = 1,
    FillColor = 2,
    FillStyle = 0,
    MarkerColor = 2,
    MarkerStyle = 1,
    Weight = 1.,
)
GM1g = PSet(
    FileName = "GM1g.root",
    DisplayName = "GM1g",
    DrawOption = "HISTE",
    LineColor = 2,
    LineWidth = 2,
    LineStyle = 1,
    FillColor = 2,
    FillStyle = 0,
    MarkerColor = 2,
    MarkerStyle = 1,
    Weight = 1.,
)

