# Generated by SampleDB
from icf.core import PSet
Mu_Run2010A_PromptReco_v4_24092010 = PSet(
	Name = 'Mu_Run2010A_PromptReco_v4_24092010',
	File = [
		# Job # 326
		# Luminosity: Unknown
		# Events: 532084
		'root://xrootd.grid.hep.ph.ic.ac.uk//store/user/as1604//ICF/automated/2010_09_26_02_03_54//SusyCAF_Tree_32_1_xKD.root',
		'root://xrootd.grid.hep.ph.ic.ac.uk//store/user/as1604//ICF/automated/2010_09_26_02_03_54//SusyCAF_Tree_14_1_qA1.root',
		'root://xrootd.grid.hep.ph.ic.ac.uk//store/user/as1604//ICF/automated/2010_09_26_02_03_54//SusyCAF_Tree_1_1_3Aa.root',
		'root://xrootd.grid.hep.ph.ic.ac.uk//store/user/as1604//ICF/automated/2010_09_26_02_03_54//SusyCAF_Tree_4_1_aSa.root',
		'root://xrootd.grid.hep.ph.ic.ac.uk//store/user/as1604//ICF/automated/2010_09_26_02_03_54//SusyCAF_Tree_25_2_PIp.root',
		'root://xrootd.grid.hep.ph.ic.ac.uk//store/user/as1604//ICF/automated/2010_09_26_02_03_54//SusyCAF_Tree_11_1_cYI.root',
		'root://xrootd.grid.hep.ph.ic.ac.uk//store/user/as1604//ICF/automated/2010_09_26_02_03_54//SusyCAF_Tree_23_1_gSY.root',
		'root://xrootd.grid.hep.ph.ic.ac.uk//store/user/as1604//ICF/automated/2010_09_26_02_03_54//SusyCAF_Tree_28_1_aK1.root',
		'root://xrootd.grid.hep.ph.ic.ac.uk//store/user/as1604//ICF/automated/2010_09_26_02_03_54//SusyCAF_Tree_24_1_bAW.root',
		'root://xrootd.grid.hep.ph.ic.ac.uk//store/user/as1604//ICF/automated/2010_09_26_02_03_54//SusyCAF_Tree_10_1_OOL.root',
		'root://xrootd.grid.hep.ph.ic.ac.uk//store/user/as1604//ICF/automated/2010_09_26_02_03_54//SusyCAF_Tree_8_1_npp.root',
		'root://xrootd.grid.hep.ph.ic.ac.uk//store/user/as1604//ICF/automated/2010_09_26_02_03_54//SusyCAF_Tree_19_1_RdW.root',
		'root://xrootd.grid.hep.ph.ic.ac.uk//store/user/as1604//ICF/automated/2010_09_26_02_03_54//SusyCAF_Tree_7_1_Sf7.root',
		'root://xrootd.grid.hep.ph.ic.ac.uk//store/user/as1604//ICF/automated/2010_09_26_02_03_54//SusyCAF_Tree_6_1_n4M.root',
		'root://xrootd.grid.hep.ph.ic.ac.uk//store/user/as1604//ICF/automated/2010_09_26_02_03_54//SusyCAF_Tree_31_1_yvn.root',
		'root://xrootd.grid.hep.ph.ic.ac.uk//store/user/as1604//ICF/automated/2010_09_26_02_03_54//SusyCAF_Tree_9_1_kzC.root',
		'root://xrootd.grid.hep.ph.ic.ac.uk//store/user/as1604//ICF/automated/2010_09_26_02_03_54//SusyCAF_Tree_15_1_HqA.root',
		'root://xrootd.grid.hep.ph.ic.ac.uk//store/user/as1604//ICF/automated/2010_09_26_02_03_54//SusyCAF_Tree_16_1_dhj.root',
		'root://xrootd.grid.hep.ph.ic.ac.uk//store/user/as1604//ICF/automated/2010_09_26_02_03_54//SusyCAF_Tree_12_1_ELs.root',
		'root://xrootd.grid.hep.ph.ic.ac.uk//store/user/as1604//ICF/automated/2010_09_26_02_03_54//SusyCAF_Tree_27_1_4Xt.root',
		'root://xrootd.grid.hep.ph.ic.ac.uk//store/user/as1604//ICF/automated/2010_09_26_02_03_54//SusyCAF_Tree_26_1_0Vn.root',
		'root://xrootd.grid.hep.ph.ic.ac.uk//store/user/as1604//ICF/automated/2010_09_26_02_03_54//SusyCAF_Tree_29_1_BBT.root',
		'root://xrootd.grid.hep.ph.ic.ac.uk//store/user/as1604//ICF/automated/2010_09_26_02_03_54//SusyCAF_Tree_5_1_6Ke.root',
		'root://xrootd.grid.hep.ph.ic.ac.uk//store/user/as1604//ICF/automated/2010_09_26_02_03_54//SusyCAF_Tree_30_1_kb0.root',
		'root://xrootd.grid.hep.ph.ic.ac.uk//store/user/as1604//ICF/automated/2010_09_26_02_03_54//SusyCAF_Tree_21_1_HFx.root',
		'root://xrootd.grid.hep.ph.ic.ac.uk//store/user/as1604//ICF/automated/2010_09_26_02_03_54//SusyCAF_Tree_33_1_n7j.root',
		'root://xrootd.grid.hep.ph.ic.ac.uk//store/user/as1604//ICF/automated/2010_09_26_02_03_54//SusyCAF_Tree_18_1_Hh4.root',
		'root://xrootd.grid.hep.ph.ic.ac.uk//store/user/as1604//ICF/automated/2010_09_26_02_03_54//SusyCAF_Tree_17_1_R2p.root',
		'root://xrootd.grid.hep.ph.ic.ac.uk//store/user/as1604//ICF/automated/2010_09_26_02_03_54//SusyCAF_Tree_13_1_Qyq.root',
		'root://xrootd.grid.hep.ph.ic.ac.uk//store/user/as1604//ICF/automated/2010_09_26_02_03_54//SusyCAF_Tree_3_1_yy0.root',
		'root://xrootd.grid.hep.ph.ic.ac.uk//store/user/as1604//ICF/automated/2010_09_26_02_03_54//SusyCAF_Tree_2_1_p2s.root',
		'root://xrootd.grid.hep.ph.ic.ac.uk//store/user/as1604//ICF/automated/2010_09_26_02_03_54//SusyCAF_Tree_20_1_mjB.root'	],
	Format = ('ICF', 2),
	Weight=1.0
)
