/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef ROOWPLUS
#define ROOWPLUS

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"

// ROOT headers
#include "TFile.h"
#include "TH1D.h"
#include "TString.h" 

class RooWPlus : public RooAbsPdf {
public:
  RooWPlus() {} ; 
  RooWPlus(const char *name, const char *title, 
	      RooAbsReal& _x,
	      RooAbsReal& _fL,
	      RooAbsReal& _fR
	  );
  RooWPlus(const RooWPlus& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new RooWPlus(*this,newname); }
  inline virtual ~RooWPlus() { }

protected:

  RooRealProxy x ;
  RooRealProxy fL ;
  RooRealProxy fR ;
  
  Double_t evaluate() const ;

private:

  Int_t rbin;
  TString dir;

  TFile *fW; // use W file to extract templates
  TH1D *mc1, *mc2, *mc3;
  
  TString pHist1, pHist2, pHist3;

  ClassDef(RooWPlus,1) // Your description goes here...
};
 
#endif
