/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef ROOWMINUSEXT
#define ROOWMINUSEXT

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
 // ROOT headers
#include "TFile.h"
#include "TH1D.h"
#include "TString.h" 
class RooWMinusExt : public RooAbsPdf {
public:
  RooWMinusExt() {} ; 
  RooWMinusExt(const char *name, const char *title,
	      RooAbsReal& _x,
	      RooAbsReal& _f1,
	      RooAbsReal& _f2,
	      RooAbsReal& _fs,
	      RooAbsReal& _fm);
  RooWMinusExt(const RooWMinusExt& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new RooWMinusExt(*this,newname); }
  inline virtual ~RooWMinusExt() { }

protected:

  RooRealProxy x ;
  RooRealProxy f1 ;
  RooRealProxy f2 ;
  RooRealProxy fs ;
  RooRealProxy fm ;
  
  Double_t evaluate() const ;

private:

 Int_t rbin;
  TString dir;

  TFile *fW; // use W file to extract templates
  TH1D *mc1, *mc2, *mc3;
  
  TString pHist1, pHist2, pHist3;

  ClassDef(RooWMinusExt,1) // Your description goes here...
};
 
#endif
