/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef ROOWPLUSEXTENDED
#define ROOWPLUSEXTENDED

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
 
// ROOT headers
#include "TFile.h"
#include "TH1D.h"
#include "TString.h" 


class RooWPlusExtended : public RooAbsPdf {
public:
  RooWPlusExtended() {} ; 
  RooWPlusExtended(const char *name, const char *title,
	      RooAbsReal& _x,
	      RooAbsReal& _fL,
	      RooAbsReal& _fR,
	      RooAbsReal& _fs);
  RooWPlusExtended(const RooWPlusExtended& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new RooWPlusExtended(*this,newname); }
  inline virtual ~RooWPlusExtended() { }

protected:

  RooRealProxy x ;
  RooRealProxy fL ;
  RooRealProxy fR ;
  RooRealProxy fs ;
  
  Double_t evaluate() const ;

private:

  Int_t rbin;
  TString dir;

  TFile *fW; // use W file to extract templates
  TH1D *mc1, *mc2, *mc3;
  
  TString pHist1, pHist2, pHist3;


  ClassDef(RooWPlusExtended,1) // Your description goes here...
};
 
#endif
