#!/usr/bin/env python

from ROOT import *

gStyle.SetOptStat(0)

f_PhotonJet = TFile.Open("../../results/Calo_ra3tight_geq3jets_G_TuneZ2_pythia6.root")
f_QCD = TFile.Open("../../results/Calo_ra3tight_geq3jets_QCD_TuneZ2_pythia6.root")
#f_Data = TFile.Open("../../results/Calo_ra3tight_geq3jets_Data.root")
for hist in ["PhotonPt_1", "PhotonPt_2", "PhotonPt_3"]:
  PhotonJetMC = f_PhotonJet.Get("StandardPlots_HT_sele/"+hist)
  #AntiSelected = f_Data.Get("StandardPlots_HT_anti/"+hist)
  AntiSelected = f_QCD.Get("StandardPlots_HT_anti/"+hist)# + f_PhotonJet.Get("StandardPlots_HT_anti/"+hist)
  #Data = f_Data.Get("StandardPlots_HT_sele/"+hist)
  QCD = f_QCD.Get("StandardPlots_HT_sele/"+hist)
  Data = QCD.Clone()
  Data.Add(PhotonJetMC)
  AntiSelected.Scale(1./AntiSelected.Integral())
  PhotonJetMC.Scale(1./PhotonJetMC.Integral())
  Data.Scale(1./Data.Integral())
  x = RooRealVar("x", "x", 70, 300)
  f = RooRealVar("f", "f", 0, 1)
  xlist = RooArgList(x)
  set = RooArgSet(xlist)
  pjetmchist = RooDataHist("pjetmc", "pjetmc", xlist, PhotonJetMC)
  antiselhist = RooDataHist("antisel", "antisel", xlist, AntiSelected) 
  data = RooDataHist("data", "data", xlist, Data)
  pjetmcpdf = RooHistPdf("pjetmc", "pjetmc", set, pjetmchist)
  antiselpdf = RooHistPdf("antisel", "antisel", set, antiselhist)
  Model = RooAddPdf("model", "model", pjetmcpdf, antiselpdf, f)
  Model.fitTo(data)

  frac = 0.18
  c = TCanvas("canvas", "canvas", 1200, 1200)
  PhotonJetMC.Scale(frac)
  PhotonJetMC.SetLineColor(kRed)
  PhotonJetMC.SetLineStyle(kDotted)
  PhotonJetMC.SetLineWidth(3)
  PhotonJetMC.GetXaxis().SetRangeUser(0, 400)
  AntiSelected.Scale(1-frac)
  AntiSelected.SetLineColor(kGreen+4)
  AntiSelected.SetLineStyle(kDashed)
  AntiSelected.SetLineWidth(3)
  AntiSelected.GetXaxis().SetRangeUser(0, 400)
  Fit = AntiSelected.Clone()
  Fit.Add(PhotonJetMC)
  Fit.SetLineColor(kBlue)
  Fit.SetLineStyle(kSolid)
  Fit.SetLineWidth(3)
  Fit.GetXaxis().SetRangeUser(0, 400)
  Fit.GetYaxis().SetTitle("Arbitrary Units")
  Data.SetMarkerStyle(20)
  Data.SetLineColor(kBlack)
  Data.GetXaxis().SetRangeUser(0, 400)
  Fit.Draw("histe")
  Data.Draw("LPsame")
  PhotonJetMC.Draw("histesame")
  AntiSelected.Draw("histesame")
  leg = TLegend(0.6, 0.6, 0.8, 0.8)
  leg.SetShadowColor(0)
  leg.SetFillColor(0)
  leg.SetLineColor(0)
  leg.AddEntry(PhotonJetMC, "#gamma+jet MC", "LP")
  leg.AddEntry(AntiSelected, "Anti-Selected Template", "LP")
  leg.AddEntry(Data, "Data", "LP")
  leg.AddEntry(Fit, "Fit Result", "LP")
  leg.Draw()
  c.SaveAs("fit_"+hist+".png")
  c.SaveAs("fit_"+hist+".eps")
  out = TFile.Open("fit_"+hist+".root", "RECREATE")
  Fit.Write()
  out.Close()
