from ROOT import *

f_Data = TFile.Open("../../results/Calo_ra3tight_geq3jets_biasDPhiCut_PhotonHad_uptoRun163817.root")
c = TCanvas("", "", 1000, 1000)
c.SetLogy()
for hist in ["pfMET_1", "pfMET_2", "pfMET_3"]:
  Sele = f_Data.Get("StandardPlots_HT_sele/"+hist)
  Anti = f_Data.Get("StandardPlots_HT_anti/"+hist)
  #Sele.Scale(1./Sele.Integral())
  Anti.Scale(Sele.Integral()/Anti.Integral())
  error = Double(0.)
  print "Predicted nEvents with MET > 100: "+str(Anti.IntegralAndError(21,80,error))
  print "Error: "+str(error)
  print "Observed nEvents with MET > 100: "+str(Sele.IntegralAndError(21,80, error))
  print "Error: "+str(error)
  Anti.SetLineColor(4)
  Anti.SetLineWidth(3)
  Anti.Draw("LP")
  Sele.SetMarkerColor(1)
  Sele.SetMarkerStyle(20)
  Sele.SetLineWidth(3)
  Sele.Draw("EPSAME")
  c.SaveAs("MET/FullRange-"+hist+".png")
  c.SaveAs("MET/FullRange-"+hist+".eps")
  Sele.GetXaxis().SetRangeUser(0., 100.)
  Anti.GetXaxis().SetRangeUser(0., 100.)
  c.SaveAs("MET/UpTo100-"+hist+".png")
  c.SaveAs("MET/UpTo100-"+hist+".eps")
  Sele.SetBinContent(21, Sele.Integral(21,80))
  Anti.SetBinContent(21, Anti.Integral(21,80))
  c.SaveAs("MET/Overflow-"+hist+".png")
  c.SaveAs("MET/Overflow-"+hist+".eps")
